version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-cost-per-tenant-lab7"
s3_bucket = "sam-bootstrap-bucket-39b2ed6f-19b4-4c33-a23f-b526b2e144b7"
s3_prefix = "serverless-saas-lab7"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"
